# Generated by Django 2.1.1 on 2018-11-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
