# Generated by Django 2.1.1 on 2018-11-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_auto_20181116_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
