# Generated by Django 2.1.1 on 2018-09-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20180927_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='act_part_tous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='act_part_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='act_prop_tous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='stay_connected',
            field=models.BooleanField(default=False),
        ),
    ]
