# Generated by Django 2.1.1 on 2018-09-29 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20180927_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amis',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
